export default {
  ONBORDINGSSCREEN: 'OnbordingsScreen',
  TAB_ROUTES:"tabRoutes",
  HOME: 'Home',
  PROFILE: 'Profile',
  EXPLORE: 'Explore',
  FAVOURITE: 'Favourite',
  NOTIFICATION: 'Notification',
  CATEGORY: 'Category',
  AUTHSTACK:"Authstack",
  HOMESTACK:"HomeStack",
  CATEGORYSTACK: "CategoryStack",
  FAVOURITESTACK: "FavouriteStack",
  NOTIFICATIONSTACK: "NotificationStack",
  PROFILESTACK: "ProfileStack",
  SHOPPINGCART: "Shoppingcart",
  PRODUCTS: 'Products',
  SEARCH: 'Search',
  STACK:'StackNavigator',
  SIGNUP:'SignUpScreen',
  SIGNIN:'LoginScreen',
  CHNGPASS:'ChangePassword',
  FRGOTPASS:'ForgotPassword',
  OTPVERF:'OtpVerification',
  PHONEVERF:'PhoneNumber'
};